// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DetailPrepsController from "./detail_preps_controller"
application.register("detail-preps", DetailPrepsController)

import FindDetailPrepsController from "./find_detail_preps_controller"
application.register("find-detail-preps", FindDetailPrepsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
